/* AUTO-GENERATED by scripts/gen-nearby-pois.mjs — do not edit by hand.
   Run `npm run nearby` to populate from the Google Places API. Until then
   these are empty so the build/labels just show the hand-placed POIs. */
export const NEARBY = {
  'bleed-1': [],
  'bleed-2': [],
}
