// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { DealData } from '../lib/types.ts'

export const DEAL: DealData = {
  "name": "The Merrimack",
  "address": "24 Merrimack St",
  "cityState": "Lowell, MA",
  "cityLong": "Lowell, Massachusetts",
  "fullAddress": "24 Merrimack St, Lowell, MA",
  "status": "For Sale",
  "docType": "Offering Memorandum",
  "coverImage": "/photos/merrimack-ext-corner.jpg"
}
