// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { PhotoPageData } from '../lib/types.ts'

export const PHOTO_PAGES: PhotoPageData[] = [
  {
    "id": "photos-1",
    "title": "Property Photos",
    "layout": "g-hero-2",
    "photos": [
      {
        "src": "/photos/merrimack-ext-corner.jpg",
        "caption": "The corner of Merrimack and John Streets — five stories of 1906 masonry"
      },
      {
        "src": "/photos/merrimack-entrance.jpg",
        "caption": "The Merrimack — main residential entrance on Merrimack Street"
      },
      {
        "src": "/photos/merrimack-lobby.jpg",
        "caption": "Resident lobby and elevator lounge"
      }
    ]
  },
  {
    "id": "photos-2",
    "title": "Property Photos",
    "layout": "g-2x2",
    "photos": [
      {
        "src": "/photos/merrimack-kitchen-galley.jpg",
        "caption": "Galley kitchen with granite counters, gas range, and track lighting"
      },
      {
        "src": "/photos/merrimack-kitchen-loft.jpg",
        "caption": "Open-plan kitchen and living area with island and high ceilings"
      },
      {
        "src": "/photos/merrimack-living.jpg",
        "caption": "Living room with oversized windows and downtown views"
      },
      {
        "src": "/photos/merrimack-loft-room.jpg",
        "caption": "Loft-style living space with original window lines"
      }
    ]
  },
  {
    "id": "photos-3",
    "title": "Property Photos",
    "layout": "g-hero-2",
    "photos": [
      {
        "src": "/photos/merrimack-bedroom.jpg",
        "caption": "Unit bedroom with double closets"
      },
      {
        "src": "/photos/merrimack-bedroom-2.jpg",
        "caption": "Bedroom with high ceilings and downtown outlooks"
      },
      {
        "src": "/photos/merrimack-bath.jpg",
        "caption": "Unit bathroom — granite vanity and full tub/shower"
      }
    ]
  }
]

export const EXEC_PHOTO: string | null = "/photos/merrimack-ext-corner.jpg"
export const HIGHLIGHT_PHOTOS: Array<string | null> = [
  "/photos/merrimack-lobby.jpg",
  "/photos/merrimack-kitchen-galley.jpg"
]
export const CITY_PHOTOS: Array<string | null> = [
  "/photos/merrimack-ext-corner.jpg",
  "/photos/merrimack-living.jpg"
]
export const COUNTY_PHOTOS: Array<string | null> = [
  "/photos/merrimack-loft-room.jpg",
  "/photos/merrimack-bedroom.jpg"
]
