// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { BrokerData } from '../lib/types.ts'

export const BROKERS: BrokerData[] = [
  {
    "name": "Brad Balletto",
    "title": "Managing Director, Investments",
    "phone": "203.307.1574",
    "email": "bballetto@northeastpcg.com",
    "photo": "/photos/team/brad-balletto.jpg"
  },
  {
    "name": "Taylor Perun",
    "title": "Senior Vice President, Investments",
    "phone": "203.307.1576",
    "email": "tperun@northeastpcg.com",
    "photo": "/photos/team/taylor-perun.png"
  }
]
