// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { DealData } from '../lib/types.ts'

export const DEAL: DealData = {
  "name": "Millbury Street Mixed Use",
  "address": "23-33 Millbury Street",
  "cityState": "Worcester, MA",
  "cityLong": "Worcester, Massachusetts",
  "fullAddress": "23-33 Millbury Street, Worcester, MA",
  "status": "For Sale",
  "docType": "Offering Memorandum",
  "descriptor": "11-Unit Mixed-Use · ±24,195 SF",
  "coverImage": "/photos/5bbdba46-2452-4e38-adb8-7a6ff7a5e2e3.jpg"
}
