// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { FinancialsData } from '../lib/types.ts'

export const FINANCIALS: FinancialsData = {
  "askingPrice": 2495000,
  "unitCount": 11,
  "buildingSf": 24195,
  "rentRoll": {
    "basis": "monthly",
    "columns": [
      {
        "key": "current",
        "label": "In-Place / mo"
      },
      {
        "key": "proForma",
        "label": "Pro Forma"
      }
    ],
    "rows": [
      {
        "group": "Commercial",
        "unit": "First Floor",
        "use": "Bakery",
        "tenant": "Bakery",
        "sf": 3440,
        "leaseEnd": "08/30/2030",
        "rents": {
          "current": 4000,
          "proForma": 4080
        }
      },
      {
        "group": "Commercial",
        "unit": "First Floor Left",
        "use": "Deli",
        "tenant": "Deli",
        "sf": 1020,
        "leaseEnd": "08/31/2020",
        "rents": {
          "current": 1020,
          "proForma": 1062.5
        }
      },
      {
        "group": "Residential",
        "unit": "25 - 1",
        "use": "4 Bed",
        "sf": 1225,
        "leaseEnd": "08/31/2026",
        "rents": {
          "current": 1895,
          "proForma": 2400
        }
      },
      {
        "group": "Residential",
        "unit": "25 - 2",
        "use": "4 Bed",
        "sf": 1225,
        "leaseEnd": "10/31/2026",
        "rents": {
          "current": 1895,
          "proForma": 2400
        }
      },
      {
        "group": "Residential",
        "unit": "25 - 3",
        "use": "4 Bed",
        "sf": 1225,
        "leaseEnd": "03/31/2027",
        "rents": {
          "current": 1783,
          "proForma": 2400
        }
      },
      {
        "group": "Residential",
        "unit": "25 - 4",
        "use": "3 Bed",
        "sf": 1225,
        "rents": {
          "current": 1895,
          "proForma": 2200
        }
      },
      {
        "group": "Residential",
        "unit": "25 - 5",
        "use": "4 Bed",
        "sf": 1225,
        "rents": {
          "current": 1895,
          "proForma": 2400
        }
      },
      {
        "group": "Residential",
        "unit": "25 - 6",
        "use": "3 Bed",
        "sf": 1225,
        "leaseEnd": "11/14/2026",
        "rents": {
          "current": 1895,
          "proForma": 2200
        }
      },
      {
        "group": "Residential",
        "unit": "33 - 1",
        "use": "4 Bed",
        "sf": 1225,
        "leaseEnd": "05/31/2021",
        "rents": {
          "current": 1495,
          "proForma": 2400
        }
      },
      {
        "group": "Residential",
        "unit": "33 - 2",
        "use": "3 Bed",
        "sf": 1225,
        "leaseEnd": "11/30/2026",
        "rents": {
          "current": 1795,
          "proForma": 2200
        }
      },
      {
        "group": "Residential",
        "unit": "33 - 3",
        "use": "3 Bed",
        "sf": 1225,
        "leaseEnd": "06/30/2027",
        "rents": {
          "current": 1895,
          "proForma": 2200
        }
      }
    ]
  },
  "ie": {
    "columns": [
      {
        "key": "current",
        "label": "In-Place / mo"
      },
      {
        "key": "proForma",
        "label": "Pro Forma"
      }
    ],
    "otherIncomeLines": [],
    "expenseLines": [
      {
        "label": "Real Estate Tax",
        "amounts": {
          "current": 29450.5,
          "proForma": 29450.5
        }
      },
      {
        "label": "Property Insurance",
        "amounts": {
          "current": 20863.52,
          "proForma": 20863.52
        }
      },
      {
        "label": "Electric",
        "amounts": {
          "current": 900,
          "proForma": 900
        }
      },
      {
        "label": "Water and Sewer",
        "amounts": {
          "current": 14646.83,
          "proForma": 14646.83
        }
      },
      {
        "label": "Trash Removal",
        "amounts": {
          "current": 2792.3,
          "proForma": 2792.3
        }
      },
      {
        "label": "Repairs and Maintenance",
        "amounts": {
          "current": 5500,
          "proForma": 5500
        }
      },
      {
        "label": "Cleaning",
        "amounts": {
          "current": 1030,
          "proForma": 1030
        }
      },
      {
        "label": "Pest Control",
        "amounts": {
          "current": 970,
          "proForma": 970
        }
      },
      {
        "label": "Professional and Legal",
        "amounts": {
          "current": 2400,
          "proForma": 2400
        }
      },
      {
        "label": "Internet",
        "amounts": {
          "current": 2040,
          "proForma": 2040
        }
      }
    ],
    "vacancyPct": 0.05,
    "mgmtPct": 0.05
  },
  "computed": {
    "rentRoll": {
      "unitCount": 11,
      "totalSf": 15485,
      "vacantCount": 0,
      "camAnnualTotal": 0,
      "byColumn": {
        "current": {
          "monthly": 21463,
          "annual": 257556,
          "psfAnnual": 16.63
        },
        "proForma": {
          "monthly": 25943,
          "annual": 311310,
          "psfAnnual": 20.1
        }
      },
      "groups": [
        {
          "group": "Commercial",
          "unitCount": 2,
          "totalSf": 4460,
          "byColumn": {
            "current": {
              "monthly": 5020,
              "annual": 60240,
              "psfAnnual": 13.51
            },
            "proForma": {
              "monthly": 5143,
              "annual": 61710,
              "psfAnnual": 13.84
            }
          }
        },
        {
          "group": "Residential",
          "unitCount": 9,
          "totalSf": 11025,
          "byColumn": {
            "current": {
              "monthly": 16443,
              "annual": 197316,
              "psfAnnual": 17.9
            },
            "proForma": {
              "monthly": 20800,
              "annual": 249600,
              "psfAnnual": 22.64
            }
          }
        }
      ],
      "unitMix": [
        {
          "use": "Bakery",
          "count": 1,
          "totalSf": 3440,
          "avgSf": 3440,
          "rentRange": {
            "current": {
              "min": 4000,
              "max": 4000
            },
            "proForma": {
              "min": 4080,
              "max": 4080
            }
          }
        },
        {
          "use": "Deli",
          "count": 1,
          "totalSf": 1020,
          "avgSf": 1020,
          "rentRange": {
            "current": {
              "min": 1020,
              "max": 1020
            },
            "proForma": {
              "min": 1063,
              "max": 1063
            }
          }
        },
        {
          "use": "4 Bed",
          "count": 5,
          "totalSf": 6125,
          "avgSf": 1225,
          "rentRange": {
            "current": {
              "min": 1495,
              "max": 1895
            },
            "proForma": {
              "min": 2400,
              "max": 2400
            }
          }
        },
        {
          "use": "3 Bed",
          "count": 4,
          "totalSf": 4900,
          "avgSf": 1225,
          "rentRange": {
            "current": {
              "min": 1795,
              "max": 1895
            },
            "proForma": {
              "min": 2200,
              "max": 2200
            }
          }
        }
      ]
    },
    "incomeExpense": {
      "byColumn": {
        "current": {
          "grossScheduledRent": 257550,
          "vacancyLoss": 12877,
          "effectiveRentalIncome": 244673,
          "otherIncome": 0,
          "egi": 244673,
          "mgmtFee": 12234,
          "totalExpenses": 92827,
          "noi": 151846
        },
        "proForma": {
          "grossScheduledRent": 311310,
          "vacancyLoss": 15566,
          "effectiveRentalIncome": 295744,
          "otherIncome": 0,
          "egi": 295744,
          "mgmtFee": 14787,
          "totalExpenses": 95380,
          "noi": 200364
        }
      }
    },
    "returns": {
      "capRateByColumn": {
        "current": 6.09,
        "proForma": 8.03
      },
      "pricePerSf": 103.12,
      "pricePerUnit": 226818,
      "grm": 9.69
    }
  }
}
