// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { StatTile } from '../lib/types.ts'

export const EXEC_TILES: StatTile[] = [
  {
    "v": "$2,495,000",
    "l": "Offering Price"
  },
  {
    "v": "6.09%",
    "l": "In-Place Cap"
  },
  {
    "v": "11",
    "l": "Total Units"
  },
  {
    "v": "$151,846",
    "l": "Net Operating Income"
  }
]

export const SUMMARY_ROWS: Array<[string, string]> = [
  [
    "Building Size",
    "24,195 SF"
  ],
  [
    "Number of Units",
    "11"
  ],
  [
    "Unit Mix",
    "(1) Bakery · (1) Deli · (5) 4 Bed · (4) 3 Bed"
  ],
  [
    "Year Built",
    "1900"
  ],
  [
    "Net Operating Income",
    "$151,846 (current)"
  ],
  [
    "Pro Forma NOI",
    "$200,364"
  ],
  [
    "Cap Rate (Cur / PF)",
    "6.09% / 8.03%"
  ]
]
