// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { ManifestEntry } from '../lib/types.ts'

export const MANIFEST: ManifestEntry[] = [
  {
    "id": "cover",
    "type": "cover",
    "title": "Cover",
    "contentModule": "cover.content.ts"
  },
  {
    "id": "toc",
    "type": "toc",
    "title": "Table of Contents"
  },
  {
    "id": "contacts",
    "type": "contacts",
    "title": "Deal Contacts"
  },
  {
    "id": "exec-summary",
    "type": "exec-summary",
    "title": "Executive Summary",
    "contentModule": "exec-summary.content.ts"
  },
  {
    "id": "highlights",
    "type": "highlights",
    "title": "Investment Highlights",
    "contentModule": "highlights.content.ts"
  },
  {
    "id": "divider-1",
    "type": "divider",
    "title": "The Property",
    "eyebrow": "01",
    "image": "/photos/toc-aerial.jpg"
  },
  {
    "id": "property-overview",
    "type": "property-overview",
    "title": "Property Overview"
  },
  {
    "id": "photos-1",
    "type": "photos",
    "title": "Exterior"
  },
  {
    "id": "photos-2",
    "type": "photos",
    "title": "Commercial Space"
  },
  {
    "id": "photos-3",
    "type": "photos",
    "title": "Unit Interiors"
  },
  {
    "id": "divider-2",
    "type": "divider",
    "title": "Financial Analysis",
    "eyebrow": "02",
    "image": "/photos/toc-aerial.jpg"
  },
  {
    "id": "rent-roll",
    "type": "rent-roll",
    "title": "Rent Roll"
  },
  {
    "id": "income-expense",
    "type": "income-expense",
    "title": "Income & Expense"
  },
  {
    "id": "divider-3",
    "type": "divider",
    "title": "Location & Market",
    "eyebrow": "03",
    "image": "/photos/toc-aerial.jpg"
  },
  {
    "id": "lifestyle-culture",
    "type": "lifestyle-culture",
    "title": "The Canal District"
  },
  {
    "id": "portfolio-map",
    "type": "portfolio-map",
    "title": "The Portfolio"
  },
  {
    "id": "employers-education",
    "type": "employers-education",
    "title": "Employers & Education"
  },
  {
    "id": "transportation",
    "type": "transportation",
    "title": "Transportation & Connectivity"
  },
  {
    "id": "location-amenities",
    "type": "location-amenities",
    "title": "Location & Amenities"
  },
  {
    "id": "development-pipeline",
    "type": "development-pipeline",
    "title": "Neighborhood Development"
  },
  {
    "id": "regional-position",
    "type": "regional-position",
    "title": "Regional Positioning"
  },
  {
    "id": "divider-4",
    "type": "divider",
    "title": "The Team",
    "eyebrow": "04",
    "image": "/photos/toc-aerial.jpg"
  },
  {
    "id": "team",
    "type": "team",
    "title": "Our Team"
  },
  {
    "id": "locations",
    "type": "locations",
    "title": "Our Locations"
  }
]
