// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { OverviewData } from '../lib/types.ts'

export const OVERVIEW: OverviewData = {
  "cards": [
    {
      "title": "Site Summary",
      "rows": [
        {
          "label": "Address",
          "value": "23-33 Millbury Street, Worcester, MA"
        },
        {
          "label": "Property Type",
          "value": "Mixed-Use"
        },
        {
          "label": "Building Size",
          "value": "24,195 SF"
        },
        {
          "label": "Lot Size",
          "value": "0.159 Acres"
        },
        {
          "label": "Year Built",
          "value": "1900"
        },
        {
          "label": "Stories",
          "value": "4"
        },
        {
          "label": "Zoning",
          "value": "BG-3"
        }
      ]
    },
    {
      "title": "Utilities",
      "rows": [
        {
          "label": "Heat",
          "value": "Forced Air"
        },
        {
          "label": "Tenant Pays",
          "value": "Electric, gas/heat (individually metered)"
        },
        {
          "label": "Landlord Pays",
          "value": "Water and sewer, trash removal, common-area electric, internet"
        }
      ]
    },
    {
      "title": "Unit Mix & Rents",
      "rows": [
        {
          "label": "Bakery",
          "value": "1 unit · 3,440 SF · $4,000"
        },
        {
          "label": "Deli",
          "value": "1 unit · 1,020 SF · $1,020"
        },
        {
          "label": "4 Bed",
          "value": "5 units · 1,225 SF · $1,495–$1,895"
        },
        {
          "label": "3 Bed",
          "value": "4 units · 1,225 SF · $1,795–$1,895"
        },
        {
          "label": "In-Place Rent",
          "value": "$21,463 / mo · $257,556 / yr"
        },
        {
          "label": "Pro Forma Rent",
          "value": "$25,943 / mo · $311,310 / yr"
        }
      ]
    },
    {
      "title": "Investment Profile",
      "rows": [
        {
          "label": "Offering Price",
          "value": "$2,495,000"
        },
        {
          "label": "Price / Unit",
          "value": "$226,818"
        },
        {
          "label": "Price / SF",
          "value": "$103.12"
        },
        {
          "label": "Current NOI",
          "value": "$151,846 · 6.09% cap"
        },
        {
          "label": "Pro Forma NOI",
          "value": "$200,364 · 8.03% cap"
        }
      ]
    }
  ]
}
