// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { PhotoPageData } from '../lib/types.ts'

export const PHOTO_PAGES: PhotoPageData[] = [
  {
    "id": "photos-1",
    "title": "Exterior",
    "layout": "g-hero-2",
    "photos": [
      { "src": "/photos/ext-2.jpg" },
      { "src": "/photos/ext-1.jpg", "objectPosition": "center 72%" },
      { "src": "/photos/ext-3.jpg", "objectPosition": "center 65%" }
    ]
  },
  {
    "id": "photos-2",
    "title": "Commercial Space",
    "layout": "g-2x2",
    "photos": [
      { "src": "/photos/comm-3.jpg" },
      { "src": "/photos/comm-4.jpg" },
      { "src": "/photos/comm-1.jpg" },
      { "src": "/photos/comm-2.jpg" }
    ]
  },
  {
    "id": "photos-3",
    "title": "Unit Interiors",
    "layout": "g-2x2",
    "photos": [
      { "src": "/photos/int-1.jpg" },
      { "src": "/photos/int-3.jpg" },
      { "src": "/photos/int-4.jpg" },
      { "src": "/photos/int-2.jpg" }
    ]
  }
]

export const EXEC_PHOTO: string | null = "/photos/exec-aerial.jpg"
export const HIGHLIGHT_PHOTOS: Array<string | null> = [
  "/photos/highlight-1.jpg",
  "/photos/9eb1556f-d9ae-4c44-bd0d-a0cf8300a3ca.jpg"
]
export const CITY_PHOTOS: Array<string | null> = [
  "/photos/3c0c5019-0c79-474c-9200-7fb5247a09be.jpg",
  "/photos/5d373a3c-39e7-4302-b337-ca44a72d3915.jpg"
]
export const COUNTY_PHOTOS: Array<string | null> = [
  "/photos/81545ac4-1e4a-4c2d-b110-9660f3a600f0.jpg",
  "/photos/455d57e0-b989-4f7a-8771-612b7a779ab7.jpg"
]
