// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { BrokerData } from '../lib/types.ts'

export const BROKERS: BrokerData[] = [
  {
    "name": "Francis Saenz",
    "title": "Vice President, Investments",
    "phone": "857.990.6803",
    "email": "fsaenz@northeastpcg.com",
    "photo": "/photos/team/francis-saenz.png"
  },
  {
    "name": "Tom Egbers",
    "title": "Associate",
    "phone": "857.990.2022",
    "email": "tegbers@northeastpcg.com",
    "photo": "/photos/team/tom-egbers.jpg"
  }
]
