// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { StatTile } from '../lib/types.ts'

export const EXEC_TILES: StatTile[] = [
  {
    "v": "$4,195,000",
    "l": "Offering Price"
  },
  {
    "v": "6.85%",
    "l": "In-Place Cap"
  },
  {
    "v": "16",
    "l": "Total Units"
  },
  {
    "v": "14,478 SF",
    "l": "Building Size"
  }
]

export const SUMMARY_ROWS: Array<[string, string]> = [
  [
    "Building Size",
    "14,478 SF"
  ],
  [
    "Number of Units",
    "16"
  ],
  [
    "Unit Mix",
    "(4) 2 Bed · (9) 1 Bed · (3) 3 Bed"
  ],
  [
    "Year Built",
    "1978"
  ],
  [
    "Net Operating Income",
    "$287,185 (current)"
  ],
  [
    "Pro Forma NOI",
    "$320,254"
  ],
  [
    "Cap Rate (Cur / PF)",
    "6.85% / 7.63%"
  ]
]
