// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { FinancialsData } from '../lib/types.ts'

export const FINANCIALS: FinancialsData = {
  "askingPrice": 4195000,
  "unitCount": 16,
  "buildingSf": 14478,
  "rentRoll": {
    "basis": "monthly",
    "columns": [
      {
        "key": "current",
        "label": "In-Place / mo"
      },
      {
        "key": "proForma",
        "label": "Pro Forma"
      }
    ],
    "rows": [
      {
        "group": "Residential",
        "unit": "1",
        "use": "2 Bed",
        "tenant": "VACANT",
        "sf": 900,
        "rents": {
          "current": 2500,
          "proForma": 2550
        }
      },
      {
        "group": "Residential",
        "unit": "2",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 1850,
          "proForma": 2050
        }
      },
      {
        "group": "Residential",
        "unit": "3",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 1700,
          "proForma": 2050
        }
      },
      {
        "group": "Residential",
        "unit": "4",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 1950,
          "proForma": 2050
        }
      },
      {
        "group": "Residential",
        "unit": "5",
        "use": "2 Bed",
        "sf": 900,
        "rents": {
          "current": 2300,
          "proForma": 2550
        }
      },
      {
        "group": "Residential",
        "unit": "6",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 1900,
          "proForma": 2050
        }
      },
      {
        "group": "Residential",
        "unit": "7",
        "use": "3 Bed",
        "sf": 1100,
        "rents": {
          "current": 2950,
          "proForma": 3050
        }
      },
      {
        "group": "Residential",
        "unit": "8",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 1850,
          "proForma": 2050
        }
      },
      {
        "group": "Residential",
        "unit": "9",
        "use": "3 Bed",
        "sf": 1100,
        "rents": {
          "current": 2650,
          "proForma": 3050
        }
      },
      {
        "group": "Residential",
        "unit": "10",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 1850,
          "proForma": 2050
        }
      },
      {
        "group": "Residential",
        "unit": "11",
        "use": "3 Bed",
        "tenant": "VACANT",
        "sf": 1100,
        "rents": {
          "current": 2950,
          "proForma": 3050
        }
      },
      {
        "group": "Residential",
        "unit": "12",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 1800,
          "proForma": 2050
        }
      },
      {
        "group": "Residential",
        "unit": "14",
        "use": "2 Bed",
        "sf": 900,
        "rents": {
          "current": 2500,
          "proForma": 2550
        }
      },
      {
        "group": "Residential",
        "unit": "15",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 1850,
          "proForma": 2050
        }
      },
      {
        "group": "Residential",
        "unit": "16",
        "use": "2 Bed",
        "sf": 900,
        "rents": {
          "current": 2400,
          "proForma": 2550
        }
      },
      {
        "group": "Residential",
        "unit": "17",
        "use": "1 Bed",
        "sf": 700,
        "rents": {
          "current": 2100,
          "proForma": 2050
        }
      }
    ]
  },
  "ie": {
    "columns": [
      {
        "key": "current",
        "label": "In-Place / mo"
      },
      {
        "key": "proForma",
        "label": "Pro Forma"
      }
    ],
    "otherIncomeLines": [
      {
        "label": "Laundry",
        "note": "coin-op",
        "amounts": {
          "current": 3302,
          "proForma": 3302
        }
      }
    ],
    "expenseLines": [
      {
        "label": "Taxes",
        "amounts": {
          "current": 41269.45,
          "proForma": 41269.45
        }
      },
      {
        "label": "Insurance",
        "amounts": {
          "current": 18898.51,
          "proForma": 16000
        }
      },
      {
        "label": "Water & Sewer",
        "amounts": {
          "current": 19283.24,
          "proForma": 19283.24
        }
      },
      {
        "label": "Electric (Common)",
        "amounts": {
          "current": 3109.52,
          "proForma": 3109.52
        }
      },
      {
        "label": "Repairs & Maintenance",
        "amounts": {
          "current": 8000,
          "proForma": 8000
        }
      },
      {
        "label": "Snow & Landscape",
        "amounts": {
          "current": 4000,
          "proForma": 4000
        }
      },
      {
        "label": "Trash Removal (Estimated)",
        "amounts": {
          "current": 6000,
          "proForma": 6000
        }
      },
      {
        "label": "Internet / Security",
        "amounts": {
          "current": 3101.76,
          "proForma": 3101.76
        }
      },
      {
        "label": "Cleaning / Pest Control",
        "amounts": {
          "current": 4676.38,
          "proForma": 4676.38
        }
      }
    ],
    "vacancyPct": 0.03,
    "mgmtPct": 0.04
  },
  "computed": {
    "rentRoll": {
      "unitCount": 16,
      "totalSf": 13200,
      "vacantCount": 2,
      "camAnnualTotal": 0,
      "byColumn": {
        "current": {
          "monthly": 35100,
          "annual": 421200,
          "psfAnnual": 31.91
        },
        "proForma": {
          "monthly": 37800,
          "annual": 453600,
          "psfAnnual": 34.36
        }
      },
      "groups": [
        {
          "group": "Residential",
          "unitCount": 16,
          "totalSf": 13200,
          "byColumn": {
            "current": {
              "monthly": 35100,
              "annual": 421200,
              "psfAnnual": 31.91
            },
            "proForma": {
              "monthly": 37800,
              "annual": 453600,
              "psfAnnual": 34.36
            }
          }
        }
      ],
      "unitMix": [
        {
          "use": "2 Bed",
          "count": 4,
          "totalSf": 3600,
          "avgSf": 900,
          "rentRange": {
            "current": {
              "min": 2300,
              "max": 2500
            },
            "proForma": {
              "min": 2550,
              "max": 2550
            }
          }
        },
        {
          "use": "1 Bed",
          "count": 9,
          "totalSf": 6300,
          "avgSf": 700,
          "rentRange": {
            "current": {
              "min": 1700,
              "max": 2100
            },
            "proForma": {
              "min": 2050,
              "max": 2050
            }
          }
        },
        {
          "use": "3 Bed",
          "count": 3,
          "totalSf": 3300,
          "avgSf": 1100,
          "rentRange": {
            "current": {
              "min": 2650,
              "max": 2950
            },
            "proForma": {
              "min": 3050,
              "max": 3050
            }
          }
        }
      ]
    },
    "incomeExpense": {
      "byColumn": {
        "current": {
          "grossScheduledRent": 421200,
          "vacancyLoss": 12636,
          "effectiveRentalIncome": 408564,
          "otherIncome": 3302,
          "egi": 411866,
          "mgmtFee": 16343,
          "totalExpenses": 124681,
          "noi": 287185
        },
        "proForma": {
          "grossScheduledRent": 453600,
          "vacancyLoss": 13608,
          "effectiveRentalIncome": 439992,
          "otherIncome": 3302,
          "egi": 443294,
          "mgmtFee": 17600,
          "totalExpenses": 123040,
          "noi": 320254
        }
      }
    },
    "returns": {
      "capRateByColumn": {
        "current": 6.85,
        "proForma": 7.63
      },
      "pricePerSf": 289.75,
      "pricePerUnit": 262188,
      "grm": 9.96
    }
  }
}
