// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { OverviewData } from '../lib/types.ts'

export const OVERVIEW: OverviewData = {
  "cards": [
    {
      "title": "Site Summary",
      "rows": [
        {
          "label": "Address",
          "value": "7 & 20 Hy-Sil Ave, Chelsea, MA"
        },
        {
          "label": "Property Type",
          "value": "Multifamily"
        },
        {
          "label": "Building Size",
          "value": "14,478 SF"
        },
        {
          "label": "Lot Size",
          "value": "0.153 Acres"
        },
        {
          "label": "Year Built",
          "value": "1978"
        },
        {
          "label": "Stories",
          "value": "3"
        }
      ]
    },
    {
      "title": "Utilities",
      "rows": [
        {
          "label": "Heat",
          "value": "Electric baseboard"
        },
        {
          "label": "Tenant Pays",
          "value": "Electric"
        },
        {
          "label": "Landlord Pays",
          "value": "Water & Sewer, Trash, Common Electric, Internet/Security"
        }
      ]
    },
    {
      "title": "Construction & Systems",
      "rows": [
        {
          "label": "Parking",
          "value": "Off-street asphalt parking lot"
        }
      ]
    },
    {
      "title": "Unit Mix & Rents",
      "rows": [
        {
          "label": "2 Bed",
          "value": "4 units · 900 SF · $2,300–$2,500"
        },
        {
          "label": "1 Bed",
          "value": "9 units · 700 SF · $1,700–$2,100"
        },
        {
          "label": "3 Bed",
          "value": "3 units · 1,100 SF · $2,650–$2,950"
        },
        {
          "label": "In-Place Rent",
          "value": "$35,100 / mo · $421,200 / yr"
        },
        {
          "label": "Pro Forma Rent",
          "value": "$37,800 / mo · $453,600 / yr"
        }
      ]
    },
    {
      "title": "Investment Profile",
      "rows": [
        {
          "label": "Offering Price",
          "value": "$4,195,000"
        },
        {
          "label": "Price / Unit",
          "value": "$262,188"
        },
        {
          "label": "Price / SF",
          "value": "$289.75"
        },
        {
          "label": "Current NOI",
          "value": "$287,185 · 6.85% cap"
        },
        {
          "label": "Pro Forma NOI",
          "value": "$320,254 · 7.63% cap"
        }
      ]
    }
  ]
}
