// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { PhotoPageData } from '../lib/types.ts'

export const PHOTO_PAGES: PhotoPageData[] = [
  {
    "id": "photos-1",
    "title": "Property Photos",
    "layout": "g-hero-2",
    "photos": [
      {
        "src": "/photos/23575d65-b2ea-4842-8252-503103d3593a.jpg",
        "caption": "Front/side street-level view with entrance canopy"
      },
      {
        "src": "/photos/f2b83b23-d15c-4c63-ad46-a62b8400c3a7.jpg",
        "caption": "Front elevation from the street"
      },
      {
        "src": "/photos/b7ce31da-f6f9-4dbb-9245-96585dbf2630.jpg",
        "caption": "Front elevation and parking lot"
      }
    ]
  },
  {
    "id": "photos-2",
    "title": "Property Photos",
    "layout": "g-2x2",
    "photos": [
      {
        "src": "/photos/13b803e2-bc3c-41b3-abb0-057f972a67c7.jpg",
        "caption": "Side/rear view with parking"
      },
      {
        "src": "/photos/6817523b-74ab-4a9d-b1ba-ad6b86d27946.jpg",
        "caption": "Side alley and rear entrance"
      },
      {
        "src": "/photos/7a704bf7-5cc5-4d28-b65a-618437b70ba8.jpg",
        "caption": "Renovated unit kitchen"
      },
      {
        "src": "/photos/4e4bb743-9abf-4800-9ee2-561dab37b241.jpg",
        "caption": "Unit kitchen"
      }
    ]
  },
  {
    "id": "photos-3",
    "title": "Property Photos",
    "layout": "g-2x2",
    "photos": [
      {
        "src": "/photos/a98450ba-11e9-4410-bde0-c9c1a25f05ba.jpg",
        "caption": "Renovated unit bathroom"
      },
      {
        "src": "/photos/989e21cd-9aee-49bd-8491-1ebd44b70aa9.jpg",
        "caption": "Original-condition unit bathroom"
      },
      {
        "src": "/photos/d0ab1b14-57aa-4ae7-af74-4b19b08e66a3.jpg",
        "caption": "Unit bedroom with baseboard heat and window AC"
      },
      {
        "src": "/photos/f1ce736e-3d67-4fee-bdf3-9c61eacb4421.jpg",
        "caption": "Unit living/dining area"
      }
    ]
  },
  {
    "id": "photos-4",
    "title": "Property Photos",
    "layout": "g-2x2",
    "photos": [
      {
        "src": "/photos/06f4cb3b-49e3-47e4-a725-07af055c247c.jpg",
        "caption": "Common coin-op laundry room"
      },
      {
        "src": "/photos/12db4011-6e58-4d00-98c0-f4b4a2a51548.jpg",
        "caption": "Basement electrical meter bank"
      },
      {
        "src": "/photos/549be766-1948-4296-b574-0e2765fa8d6d.jpg",
        "caption": "Fire alarm control panel"
      },
      {
        "src": "/photos/5462e8cb-08e1-4375-bda0-2717cc69d030.jpg",
        "caption": "Aerial showing the building and street frontage"
      }
    ]
  },
  {
    "id": "photos-5",
    "title": "Property Photos",
    "layout": "g-2x2",
    "photos": [
      {
        "src": "/photos/40a4d6af-23da-4db0-b532-1619938a6ecd.jpg",
        "caption": "Aerial of the rear of the building"
      },
      {
        "src": "/photos/012be568-59e6-4ce2-a424-2b4df5b4384d.jpg",
        "caption": "Aerial showing rooftop and neighborhood context"
      },
      {
        "src": "/photos/0a95fa05-b97f-47c5-8cf4-c1ba04faf458.jpg",
        "caption": "Wide aerial of the surrounding area"
      },
      {
        "src": "/photos/6aed1cc6-f15b-42bd-a0fc-4ac29f11853a.jpg",
        "caption": "Wide aerial toward Boston Harbor"
      }
    ]
  }
]

export const EXEC_PHOTO: string | null = "/photos/f2b83b23-d15c-4c63-ad46-a62b8400c3a7.jpg"
export const HIGHLIGHT_PHOTOS: Array<string | null> = [
  "/photos/b7ce31da-f6f9-4dbb-9245-96585dbf2630.jpg",
  "/photos/13b803e2-bc3c-41b3-abb0-057f972a67c7.jpg"
]
export const CITY_PHOTOS: Array<string | null> = [
  "/photos/chelsea-drone-1.jpg",
  "/photos/chelsea-drone-2.jpg"
]
export const COUNTY_PHOTOS: Array<string | null> = [
  "/photos/bf0abdd0-1b7c-43f8-b837-20dfbaa79d18.jpg",
  "/photos/ea627ca6-5da4-4acd-b06a-6566b1794dd3.jpg"
]
