/* AUTO-GENERATED by scripts/gen-marker-logos.mjs — do not edit by hand.
   Maps a marker `name` to a downloaded brand-logo path under /public/logos/markers/. */
export const MARKER_LOGOS = {
  "Dunkin'": "/logos/markers/dunkindonuts-com.png",
  "Stop & Shop": "/logos/markers/stopandshop-com.png",
  "Walgreens": "/logos/markers/walgreens-com.png",
  "Thomaston Savings Bank (Main Office)": "/logos/markers/thomastonsavingsbank-com.png",
  "Webster Bank": "/logos/markers/websterbank-com.png",
  "NAPA Auto Parts": "/logos/markers/napaonline-com.png",
  "Bus Stop — South Main St": "/logos/markers/cttransit-com.png"
}
