// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { StatTile } from '../lib/types.ts'

export const EXEC_TILES: StatTile[] = [
  {
    "v": "$15,000,000",
    "l": "Offering Price"
  },
  {
    "v": "5.44%",
    "l": "In-Place Cap"
  },
  {
    "v": "53",
    "l": "Total Units"
  },
  {
    "v": "$815,528",
    "l": "Net Operating Income"
  }
]

export const SUMMARY_ROWS: Array<[string, string]> = [
  [
    "Building Size",
    "66,764 SF"
  ],
  [
    "Number of Units",
    "53"
  ],
  [
    "Unit Mix",
    "(12) One Bed · (34) Two Bed · (1) Three Bed · (6) Commercial"
  ],
  [
    "Year Built",
    "1906"
  ],
  [
    "Net Operating Income",
    "$815,528 (current)"
  ],
  [
    "Pro Forma NOI",
    "$1,224,006"
  ],
  [
    "Cap Rate (Cur / PF)",
    "5.44% / 8.16%"
  ]
]
