// AUTO-GENERATED by scripts/inject.mjs — DO NOT EDIT (protected data tier)
import type { OverviewData } from '../lib/types.ts'

export const OVERVIEW: OverviewData = {
  "cards": [
    {
      "title": "Site Summary",
      "rows": [
        {
          "label": "Address",
          "value": "24 Merrimack St, Lowell, MA"
        },
        {
          "label": "Property Type",
          "value": "Mixed-Use"
        },
        {
          "label": "Building Size",
          "value": "66,764 SF"
        },
        {
          "label": "Lot Size",
          "value": "0.27 Acres"
        },
        {
          "label": "Year Built",
          "value": "1906 · renov. 2016"
        },
        {
          "label": "Stories",
          "value": "5"
        },
        {
          "label": "Zoning",
          "value": "DMU (Downtown Mixed Use)"
        },
        {
          "label": "Rentable SF",
          "value": "58,884 SF"
        },
        {
          "label": "Sprinklers",
          "value": "Wet system"
        },
        {
          "label": "Elevator",
          "value": "Yes (serviced under contract)"
        },
        {
          "label": "Opportunity Zone",
          "value": "Yes"
        },
        {
          "label": "Submarket",
          "value": "Downtown Lowell"
        }
      ]
    },
    {
      "title": "Utilities",
      "rows": [
        {
          "label": "Metering",
          "value": "Individually metered"
        },
        {
          "label": "Landlord Pays",
          "value": "Gas, Electric (CAM), Water & Sewer, Trash"
        }
      ]
    },
    {
      "title": "Construction & Systems",
      "rows": [
        {
          "label": "Construction",
          "value": "Masonry"
        }
      ]
    },
    {
      "title": "Unit Mix & Rents",
      "rows": [
        {
          "label": "One Bed",
          "value": "12 units · 749 SF · $1,785–$1,960"
        },
        {
          "label": "Two Bed",
          "value": "34 units · 1,190 SF · $1,915–$2,200"
        },
        {
          "label": "Three Bed",
          "value": "1 unit · 1,044 SF · $2,385"
        },
        {
          "label": "Commercial",
          "value": "6 units · 1,398 SF · $625–$6,987"
        },
        {
          "label": "In-Place Rent",
          "value": "$111,185 / mo · $1,334,220 / yr"
        },
        {
          "label": "Pro Forma Rent",
          "value": "$151,322 / mo · $1,815,864 / yr"
        }
      ]
    },
    {
      "title": "Investment Profile",
      "rows": [
        {
          "label": "Offering Price",
          "value": "$15,000,000"
        },
        {
          "label": "Price / Unit",
          "value": "$283,019"
        },
        {
          "label": "Price / SF",
          "value": "$225.00"
        },
        {
          "label": "Cap Rate (T12)",
          "value": "$879,242 NOI · 5.86% cap"
        },
        {
          "label": "Current NOI",
          "value": "$815,528 · 5.44% cap"
        },
        {
          "label": "Pro Forma NOI",
          "value": "$1,224,006 · 8.16% cap"
        }
      ]
    },
    {
      "title": "Debt Assumptions (Workbook Model)",
      "rows": [
        {
          "label": "Interest Rate",
          "value": "2.53% · 30-yr amortization"
        },
        {
          "label": "Loan Amount",
          "value": "$11,250,000 (75% LTV)"
        },
        {
          "label": "Annual Debt Service",
          "value": "$535,521"
        },
        {
          "label": "DSCR",
          "value": "1.52x"
        },
        {
          "label": "Cash-on-Cash (Cur / PF)",
          "value": "7.47% / 18.36%"
        }
      ]
    }
  ]
}
