/* ═══════════════════ 250 DANBURY ROAD — FLYER DATA ═══════════════════
   Four-page investment brief for 250 Danbury Rd (Rte 7), Wilton, CT.
   Content transcribed from 250_Danbury_Rd_Investor_Brief.docx.
   Photos: drop files in public/photos/ (see `photos` below).               */

export const FIRM_BIO =
  'Northeast Private Client Group is a relationship-driven investment real estate firm delivering institutional-level expertise, service, and value to private investors of multifamily, mixed-use, and retail real estate.'

const U = 'https://northeastpcg.com/wp-content/uploads'
export const BROKERS = [
  { name: 'Taylor Perun', title: 'Senior Vice President, Investments', phone: '(203) 307-1576', email: 'tperun@northeastpcg.com', photo: `${U}/2021/11/Taylor-Perun-430x488.png` },
  { name: 'Derek Mahabir', title: 'Investment Associate', phone: '(203) 751-1187', email: 'dmahabir@northeastpcg.com', photo: `${U}/2023/12/Derek-Mahabir-002-430x488.jpg` },
]

export const DANBURY = {
  name: '250 Danbury Road',
  cityState: 'Wilton, Connecticut',
  addresses: '250 Danbury Road (Route 7)',
  eyebrow: 'For Sale · Development Site',
  url: 'northeastpcg.com',

  // Photos — drop these files into public/photos/. Any that are missing
  // simply render as a neutral placeholder tile, so the flyer is complete
  // before the photos arrive.
  photos: {
    hero: '/photos/hero.jpg',          // Page 1 cover — exterior / corner
    gisMap: '/photos/gis-map.png',     // Page 2 — GIS site map (auto-generated by make-map.cjs)
    building: '/photos/building.jpg',  // Page 3 — building detail (optional)
    context: '/photos/context.jpg',    // Page 4 — streetscape / context
  },
  gisCaption: 'Subject parcel outlined (Map-Block-Lot 57-22) · 0.90-ac corner at Route 7 · Imagery © Esri · Parcel data: CT OPM / Wilton GIS',

  // Lead paragraph (Page 2 summary opener)
  lead:
    '250 Danbury Road is a historic c.1792 building of ±3,640 SF on a 0.90-acre corner lot along Wilton’s Route 7 (Danbury Road) corridor — steps from Town Hall, Wilton Center, and the Wilton train station, and served by public water and sewer.',

  // Cover stat strip
  coverStats: [
    { v: '$1.2M', l: 'Asking Price' },
    { v: '0.90 AC', l: 'Corner Lot' },
    { v: '±3,640 SF', l: 'Building' },
    { v: 'c.1792', l: 'Year Built' },
    { v: 'OL-1', l: 'Overlay Zone' },
    { v: 'Office', l: 'Current Use' },
  ],

  // Page 2 — fuller narrative
  overview: [
    'Historic corner property on Wilton’s Route 7 corridor, steps from Town Hall and the Wilton train station. Leased as office today, the asset carries income from day one while offering a residential-conversion angle through the town’s new OL-1 Danbury Road East overlay and a historic adaptive-use permit.',
    'The 0.90-acre corner lot already conforms to the overlay’s 0.75-acre minimum, so a buyer can pursue conversion without assemblage or a variance. This is a small-scale value-add and preservation play — not a ground-up multifamily site — best suited to an investor who values optionality and historic character over raw density.',
  ],

  // Page 2 — Deal at a Glance (key facts)
  facts: [
    { label: 'Asking Price', value: '$1,200,000', accent: true },
    { label: 'Location', value: '250 Danbury Rd (Rte 7), Wilton, CT' },
    { label: 'Traffic Count', value: '±25,000 cars/day (Rte 7)' },
    { label: 'Lot', value: '0.90 ac (39,204 SF) · corner' },
    { label: 'Improvements', value: 'Historic c.1792 building, ±3,640 SF, 2-story' },
    { label: 'Current Use', value: 'Office (legal non-conforming)' },
    { label: 'Zoning', value: 'R-1A base + OL-1 Danbury Rd East overlay' },
    { label: 'Utilities', value: 'Public water & sewer' },
    { label: 'Assessed / Tax', value: '$551,530 / ≈ $13,460 (2025)' },
    { label: 'Residential Cap', value: '0.25 FAR ≈ 9,800 SF · 39 ft / 3 stories' },
    { label: 'Affordability', value: '10% of units · 2 parking / unit' },
  ],

  // Page 3 — OL-1 Danbury Road East Overlay District (§29.6.G.2.1)
  overlay: {
    title: 'OL-1 Danbury Road East Overlay District',
    subtitle: 'Town of Wilton Zoning Regulations · §29.6.G.2.1',
    map: '/photos/overlay-map.jpg',
    mapCap: 'OL-1 Danbury Road East Overlay District within the Greater Wilton Center study area · Source: Town of Wilton Planning & Zoning',
    purpose: [
      'Adopted by the Town of Wilton to facilitate neighborhood-scaled, economically and environmentally sustainable multi-family development along the Danbury Road (Route 7) corridor — including affordable housing — while protecting the area’s residential character.',
      'The overlay sits on top of the existing R-1A / R-2A single-family zoning. Existing uses remain legal, and an owner may elect to develop under the overlay (subject to P&Z Commission approval) or keep the underlying zoning.',
    ],
    // Bulk & development standards (§29.6.G.2.1.D)
    standards: [
      { label: 'Permitted Use', value: 'Single-family detached & attached dwellings' },
      { label: 'Min. Lot Size', value: '0.75 acres' },
      { label: 'Max. Height', value: '39 ft / 3 stories' },
      { label: 'Max. Density', value: '0.25 FAR' },
      { label: 'Building Coverage', value: '40% max' },
      { label: 'Impervious Coverage', value: '70% max' },
      { label: 'Setbacks', value: '20 ft front · 10 ft side / rear' },
      { label: 'Affordable Housing', value: '≥ 10% of units' },
      { label: 'Parking', value: '2 spaces / unit (none in front)' },
    ],
    // Why the overlay matters for this specific parcel
    whatItMeans: [
      'The 0.90-ac corner lot already exceeds the 0.75-ac overlay minimum — no variance or assemblage needed.',
      'Adaptive reuse of the historic c.1792 building may allow up to four attached units within the preserved structure (§29-5.C.5).',
      'As a corner lot, both Route 7 and Old Hwy are treated as primary frontages with street-facing façades.',
      'The existing structure is expressly declared conforming when maintained and integrated into the development.',
    ],
  },

  // Page 4 — Paths to Value
  paths: [
    {
      tag: 'Lease as Office',
      body: 'Re-tenant the building under its existing legal non-conforming office use.',
    },
    {
      tag: 'Residential Conversion (OL-1)',
      body: 'Attached / townhouse dwellings plus up to four units inside the preserved historic building; the lot already meets the overlay minimum.',
    },
    {
      tag: 'Mixed-Use Adaptive-Use (§29-5.C.5)',
      body: 'A historic adaptive-use permit allowing office use plus residence apartments within one building.',
    },
    {
      tag: '§8-30g Affordable Housing',
      body: 'The only route to materially higher density; requires ≥ 30% deed-restricted affordable units.',
    },
  ],

  // Page 4 — Highlights & Watch Items
  highlights: [
    'Lot already conforms to the overlay 0.75-ac minimum — no assemblage or variance needed.',
    'Optionality: office income in place today, residential / entitlement upside later.',
    'Public water & sewer; walkable to the Wilton train station and Wilton Center.',
    'Historic character supports a premium preservation positioning; existing building deemed conforming.',
  ],
  watch: [
    'Small scale — 0.25 FAR (≈ 9,800 SF); OL-1 is not a conventional apartment building.',
    'Residential needs a discretionary special permit plus a 10% affordable component.',
    'Confirm the OL-1 boundary and the non-conforming status with Wilton P&Z.',
    'Historic preservation / design review likely required for any conversion.',
  ],

  // Page 4 — For Discussion + closing photos
  forDiscussion: [
    'Strategy: hold for office income, convert to residential, or play for land / entitlement value?',
    'Appetite for an affordable component or a §8-30g approach to unlock more units?',
    'Target hold period and return threshold, given the small-scale envelope?',
  ],
  closingPhotos: [
    { src: '/photos/close-1.jpg', cap: 'Route 7 frontage & corridor' },
    { src: '/photos/close-2.jpg', cap: 'Overhead — site & parking' },
    { src: '/photos/close-3.jpg', cap: 'Aerial — Wilton Center context' },
  ],
}
