/* AUTO-GENERATED — drive-time isochrones from 613-615 Main St, Ridgefield.
   Road-network polygons (public Valhalla, costing:auto), Douglas-Peucker
   simplified + Chaikin-smoothed for soft rounded bands, stored as Google-encoded
   polylines. Largest contour first so inner bands paint on top. */

export const ISOCHRONES = [
  { min: 60, color: '0xC0392B', enc: 'cgf~Fvri}L~jCtnCh`BjpCtu@xqC|JlsCu]~tCfBhwBdd@ryAffA|{@bhBf^|a@hl@gb@jz@qhBlhAwnDpvAs~AprBoNvnCr_AzjDxoC~fEtvA|aDr]z|BqYxwAurAvr@qTje@ng@~WpeBrJrcDw@jhAlP_Qrc@ilBxv@qgE~iAkgC`uAagA``ByFbkBlw@dvBlw@dbAhw@hNhw@uc@fw@swAbt@kr@~p@eMzm@~Uvj@d{@jw@j`@|cArEppAeSd}A_n@|`A}Bvd@ff@nHjqAwQl|B{_@bqAan@ve@i|@qCmjA{n@u}@mJ}p@`Xcd@p|@mW`aB_Svy@sNnRgJyRyEcz@cWm^gh@wBoy@zVwjAnr@ka@p}@zEthAfo@vsApxAv~Ajj@`u@wAjK}o@k\\a~AcfA}tAw_@wkArDqbA|j@my@fqAmDndApn@vw@ncB~j@nxCf^xxBfpAdyAfbCpy@ftD|YffFhzAd_EvzC~wC`{EzpBn{GviAx}Cvm@~_@vQw{AgHmyEgd@ifCzCgs@~m@|]`xA~pBfbCvt@xnBoEj{AyaA|gAa~Blt@um@hw@r`@`z@~pBz|@haEt_AthCfgA~oAxnAfWhvAk_@z}AtGjsBtp@zhCvyAh~CxbCzsDxvA|gAvj@{a@EumCek@qyF}OwjDhI{{Apd@_Mz_Ax_Atu@fFrk@mq@na@_kBjWudDnu@mnBpsAex@tqB}AxoCfr@pgAfTHwG{fAue@aoCycAieBamAq{@kvAuQw_B~UciBkKgpA{n@mw@irAu^wuByEei@aWja@gh@|mBoy@nzDsjAvbCec@`kAjBhSxi@mb@hqAjKfgAf{@d}@bkBbs@zzC~h@|wB~eAztA~bBxq@~_CzN~|C~JvzAdGrXlCsg@R{iB~Nw}@n^wQ|m@fXj}@jdAv_@l[dBoKmYit@aw@g}AuWmw@rEqQzd@hRfdAbx@ziAt[joAF~tAe[rzAsw@j[oo@{a@ig@eaBc_@i`D_WgsBgg@cfAqw@}XygAbRcxAja@{y@np@s[v_Ap@znAz^hb@|KiH}Dyt@{WmaBwj@es@k[{DcLng@fAtuArPvwAoUvyAs}@t{AweBt}AymCjpBukB`cCsiAvuCqg@lhDoEvaBrQ`[tj@si@vcAipBx|AidA||AeX||AzQ`}A|}@b}Ar\\rsAuBdjA}c@v`AgeAdw@sa@h_@\\jGrc@qNdgAof@vw@uDjh@b[|X||@lIv~AxYr_@`j@s]jz@w|AtjA{{Cni@wvBjHsqAwVml@}w@gGwJgWl`@ig@rmAiw@vzBigAvdAks@pNk_@me@oKo{AnF}bA_Kij@k^uQ{q@|DieAxqAa\\r~CdKnkFht@hxHr}A|fGr[nuEkd@`dDifBtrBghD|~@a~BfK{sAof@ui@ezAOm~@uPub@{a@}Fcs@xRidAi@wm@mUgWoj@u@s_AzSu_B_k@{_CykB}_DwlDc`EqmF{iEodKssEo{Ok}EorTegFkiYa~D{pR}tCgxKwkBs_EubA|Vcu@_Wsg@}fAaZyvBoLufD}l@sbDkmAo~CymBmzCgnCgvCgwAyyBk`@k}ArT}`ApkAod@zc@upAuAy|Bmi@}hDaqAcuEky@_tBya@yRcJflAnKjmDi}@btBahCvz@{rElAs}G{u@waFy}@yeDyeA}iBumA}m@uuAmO{|@~Lad@pk@gK`jAlKfRsYoc@y`Ai{A_hBasCcoCmgB}tA{{@uZiPr]hYxwAgFvq@yg@tKmiAkX}jBk~@a|@gZcMzGv_@`l@vnAfpAt]f|AkQbhBkbA`tBksB~_CefBd}A_yAjz@wkApWq~@gIsf@ma@sNoy@jGuqAh_@{iBaFuiAim@si@utAqI_|BpTkiA|b@uVhq@|Yr_AplA~mAl^tcCyMjyD_|@`oFgjBvdHccAbkFe\\jqD|HvwBzo@`~@}Md|@{mAhz@wmClx@umEpv@_|Cth@ijBxZsx@~L_GB`\\`c@~`A|fA~eBzjB' },
  { min: 45, color: '0xE67E22', enc: 'whl}Ff~{~Lj|CbgDl}AbsCn^d_Co^bkBk}AdwAeWfdA`m@hq@fsBj^pyDnKt~B~_@vcApt@zHbiA_p@v}Ao~@ldAamAbk@q{AzQajBkEyr@tAjBxJpy@zSxpB|\\djAjv@tc@zoA}@fiBmg@vbC_BjkBna@|sA~fAr|@llBfe@~{@rTpK`D{b@qJksAc[qwAbSu{AlcA{_BrsB_dBzcDca@tvCt_@liCpbBd|BneD|nBvqBzeB`~@v|AlJrsAig@pjAeEjbBzZdzB||@`rC|~AziDlhAbqAvq@qEd[i~ArDawDzW_aCfk@akAn~@cUzqA|^jh@mIEys@uh@e~AgrAmhC_a@g{AbN{m@j_Aq@npBtj@fwA{C~}@qt@vd@ceBnKwuCzj@qxAhjAk[viBv_@biCz|AbyBvvBfiBnpCjyAjjDjiAbdE|}B~|AlrDaH`gFcoBp{GivErlFw{Cr}DgaBrnCwf@t_BvQtxAeOtqAcr@vjAcuAvcAcxBrhAgfApmAmTlrAh[jwAdmAnx@jGtYi|@cCcbC}a@ygEcaCowKi`FcgRq_IyvXu~Kmf_@ywHgqV_qEa|MejB{fEgCjlAc\\nm@{t@vNumAaNofB}l@is@eHa@nZbq@f_AjdB|cBte@ljA{V`q@ouAnWetC]{sAp]sS~|@tj@n|AzjB~{Bb~@beBhQfnAmYhw@ifAl`@}eAtFueAcQkeAyj@aeAqdAee@sdAgEudArXsdArx@udA`Ncf@mZsG_eA~TooBps@i~A~KcmAoY}{@_aAwj@ohBmw@oz@edAqL{pAj_@q}AlmAq{@~^qYiMlFu{@lh@cjBxFquAyX_aAmz@ql@a|A_XmnAgw@w`AmvAas@yuBme@_uCy`Ayx@c|Aja@owBp}ByrCvyEsaAd_ErMrdDx~A`jCbpDnoBxkBd{Apg@|fAsZpr@{~Af^gdA`t@qi@~iAyN|_BvIvuBlY`xA~h@jz@px@t\\dhA?|j@rg@vMdpAqM|xBuj@laDiuAb}Ay_CtXmjDwi@}tEenB}xCuy@{|AgE{`@dm@bYtaBbD~hA{Nhp@{c@rW{x@?cC`i@vp@`sApfB`}B' },
  { min: 30, color: '0xF39C12', enc: 'yyn|Fxoc_M`mEp}@ndCtu@|{@zm@qJ~e@esAf^yt@d{AoVdxCvE`uEbd@|qG`@`mFab@~gEefA`cDgjB`~BaTlnAb`Az^hvCyNnlFk~@n{E}`@ljEoClyD|WlhDlu@~`CdeAryAztAfr@tdBxJltBv_@rlArt@xd@piA}@l~Awh@vgAq|@~p@kpAfZedBpC_xBra@uuAx_Ais@z}A_Q~{BhO~iAiL~W}i@_XqgA_jAeeBqYyjBzTmpBheAavBvuBw{BpzAsbCh_AmiCbd@kpC|HgwC~SseB~^}s@`j@iB`u@hm@|RqTiMkxAoo@g|CsqAc`FebBshEwrBcqDgcCsyCwsCcbCi_B}cAyj@sEtGpv@d|@vtBfDjgBuq@zyAqiBllAoaD|~@qmBpZuy@}GuEil@dl@wpAhOsbAoKot@ih@kf@eeAgXyoAfDizAzb@}dBhaAooB|_Bs|ArNyiAw`A}v@_rCad@icFyp@ibDo}@gaBejAe`@}vAz^mmA~A}cAwXoz@qu@_q@mrAuQsOtK`q@`k@xsBjjArvDf[`pDwQniDw`A~bD{oBn|CyqBttBusB|lAsuBde@owBq@{e@lMvi@l]l{Blm@' },
  { min: 15, color: '0x27AE60', enc: 'apv{Ff}l_Mpc@nbDnn@~}Bjy@ryAhdAfu@doAvPnn@zXxMz`@}P|h@uq@~p@{Lrm@zUdj@rz@xf@j_Bjc@hgAxDdo@{WbWqv@?cuAjTce@xi@|Hd_A~x@ptA~hB`yA|c@n}Ae_@~aBedBjfBgiDf{@{_C`PovAcYcm@idAwCgc@iZeB}p@z\\ogAz}@c~AlVecAcOkh@sv@mMa~AlK}}@aHy]q]l@as@p`@qhAyV_]gpAvLuiChx@acE~cBifD~}@oiC~WulB_L}oA_r@i}@yf@yj@s[cXmPsEgEdCdc@~MrmAvX~wB' },
]
