/* AUTO-GENERATED by scripts/gen-tenant-logos.mjs — do not edit by hand.
   Maps a tenant `name` to a downloaded logo under /public/logos/tenants/. */
export const TENANT_LOGOS = {
  "Nancy O": "/logos/tenants/nancy-o.jpg",
  "Tutoring Club": "/logos/tenants/tutoring-club.png",
  "Legacy Martial Arts": "/logos/tenants/legacy-martial-arts.png",
  "HIGHLIFE": "/logos/tenants/highlife.svg",
  "Talbots": "/logos/tenants/talbots.png",
  "DiMaggio Hair Design": "/logos/tenants/dimaggio-hair-design.jpg",
  "Southwest Café": "/logos/tenants/southwest-caf.png",
  "Ridgefield Organics": "/logos/tenants/ridgefield-organics.webp",
  "Ross Bakery & Café": "/logos/tenants/ross-bakery-caf.png",
  "À Table": "/logos/tenants/table.webp",
  "Kick Fit": "/logos/tenants/kick-fit.png"
}
